#!/bin/bash

#set -x  # echo on

declare -a collection=(
#    "Global/Anjuta"
#    "Global/Ansible"
#    "Global/Archives"
#    "Global/Bazaar"
#    "Global/BricxCC"
#    "Global/Calabash"
#    "Global/Cloud9"
#    "Global/CodeKit"
#    "Global/CVS"
#    "Global/DartEditor"
#    "Global/Dreamweaver"
#    "Global/Dropbox"
#    "Global/Eclipse"
#    "Global/EiffelStudio"
#    "Global/Emacs"
#    "Global/Ensime"
#    "Global/Espresso"
#    "Global/FlexBuilder"
#    "Global/GPG"
#    "Global/JDeveloper"
#    "Global/JEnv"
    "Global/JetBrains"
#    "Global/Kate"
#    "Global/KDevelop4"
#    "Global/Lazarus"
#    "Global/LibreOffice"
#    "Global/Linux"
#    "Global/LyX"
#    "Global/macOS"
#    "Global/Matlab"
#    "Global/Mercurial"
#    "Global/MicrosoftOffice"
#    "Global/ModelSim"
#    "Global/Momentics"
#    "Global/MonoDevelop"
#    "Global/NetBeans"
#    "Global/Ninja"
#    "Global/NotepadPP"
#    "Global/Otto"
#    "Global/Redcar"
#    "Global/Redis"
#    "Global/SBT"
#    "Global/SlickEdit"
#    "Global/Stata"
#    "Global/SublimeText"
#    "Global/SVN"
#    "Global/SynopsysVCS"
#    "Global/Tags"
#    "Global/TextMate"
#    "Global/TortoiseGit"
#    "Global/Vagrant"
#    "Global/Vim"
#    "Global/VirtualEnv"
#    "Global/VisualStudioCode"
#    "Global/WebMethods"
#    "Global/Windows"
#    "Global/Xcode"
#    "Global/XilinxISE"
#    "Actionscript"
#    "Ada"
#    "Agda"
#    "Android"
#    "AppceleratorTitanium"
#    "AppEngine"
#    "ArchLinuxPackages"
#    "Autotools"
#    "CakePHP"
#    "CFWheels"
#    "C"
#    "C++"
#    "ChefCookbook"
#    "Clojure"
#    "CMake"
#    "CodeIgniter"
#    "CommonLisp"
#    "Composer"
#    "Concrete5"
#    "Coq"
#    "CraftCMS"
#    "CUDA"
#    "Dart"
#    "Delphi"
#    "D"
#    "DM"
#    "Drupal"
#    "Eagle"
#    "Elisp"
#    "Elixir"
#    "Elm"
#    "EPiServer"
#    "Erlang"
#    "ExpressionEngine"
#    "ExtJs"
#    "Fancy"
#    "Finale"
#    "ForceDotCom"
#    "Fortran"
#    "FuelPHP"
#    "Gcov"
#    "GitBook"
#    "Go"
    "Gradle"
#    "Grails"
#    "GWT"
#    "Haskell"
#    "Idris"
#    "IGORPro"
    "Java"
#    "Jboss"
#    "Jekyll"
#    "Joomla"
#    "Julia"
#    "KiCad"
#    "Kohana"
#    "Kotlin"
#    "LabVIEW"
#    "Laravel"
#    "Leiningen"
#    "LemonStand"
#    "Lilypond"
#    "Lithium"
#    "Lua"
#    "Magento"
#    "Maven"
#    "Mercury"
#    "MetaProgrammingSystem"
#    "Nanoc"
#    "Nim"
#    "Node"
#    "Objective-C"
#    "OCaml"
#    "Opa"
#    "OpenCart"
#    "OracleForms"
#    "Packer"
#    "Perl"
#    "Phalcon"
#    "PlayFramework"
#    "Plone"
#    "Prestashop"
#    "Processing"
#    "PureScript"
#    "Python"
#    "Qooxdoo"
#    "Qt"
#    "Rails"
#    "R"
#    "RhodesRhomobile"
#    "ROS"
#    "Ruby"
#    "Rust"
#    "Sass"
#    "Scala"
#    "Scheme"
#    "SCons"
#    "Scrivener"
#    "Sdcc"
#    "SeamGen"
#    "SketchUp"
#    "Smalltalk"
#    "Stella"
#    "SugarCRM"
#    "Swift"
#    "Symfony"
#    "SymphonyCMS"
#    "Terraform"
#    "TeX"
#    "Textpattern"
#    "TurboGears2"
#    "Typo3"
#    "Umbraco"
#    "Unity"
#    "UnrealEngine"
#    "VisualStudio"
#    "VVVV"
#    "Waf"
#    "WordPress"
#    "Xojo"
#    "Yeoman"
#    "Yii"
#    "ZendFramework"
#    "Zephir"
)

path_to_gitignore=".gitignore"

for i in "$@"
do
case $i in
    -p=*|--path=*)
    path_to_gitignore="${i#*=}"
    shift # past argument=value
    ;;
    *)
          # unknown option
    ;;
esac
done

function writeln_separator {
    echo "# ---------------------------------------------------------------------------" >> "$1"
}

function donwload_gitignore {
    wget -qO- "$1" >> "$2"
}

if [ -n "$collection" ]; then
    rm "$path_to_gitignore" 2> /dev/null  # redirect the error message
    touch "$path_to_gitignore"

    writeln_separator "$path_to_gitignore"
    for i in "${collection[@]}"
    do
        echo "# https://github.com/github/gitignore/blob/master/$i.gitignore" >> "$path_to_gitignore"
        echo "" >> "$path_to_gitignore"
        
        donwload_gitignore "https://raw.githubusercontent.com/github/gitignore/master/$i.gitignore" "$path_to_gitignore"
        
        echo "" >> "$path_to_gitignore"
        writeln_separator "$path_to_gitignore"
    done
fi
